#!/usr/bin/bash

alias vim="$VIM"
alias v="$VIM"
alias python="python3"
alias pip="pip3"
alias wsl="wsl.exe"
alias dot="cd ~/dotfiles"

alias cat="bat"
alias head="coreutils head"

# eza commands
alias ls="eza --color=always --long --git --no-filesize --icons=always --no-time --no-user --no-permissions"
alias ll="eza -l"
alias la="eza -la"
alias lla="eza -Tla"
alias tree="eza -T"
alias ltree="eza -Tl"

