#!/usr/bin/bash

alias vim="$VIM"
alias v="$VIM"
alias python="python3"
alias pip="pip3"
alias wsl="wsl.exe"
alias dot="cd ~/.dotfiles"

alias cat="bat"
alias head="coreutils head"
# exa commands
alias ls="exa"
alias ll="exa -l"
alias la="exa -la"
alias lla="exa -Tla"
alias tree="exa -T"
alias ltree="exa -Tl"

