palette = "catppuccin_frappe"
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\

$cmd_duration $jobs $time\
$line_break\
$python\
$character"""

[fill]
symbol = " "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"

[git_metrics]
disabled = false

[git_commit]
commit_hash_length = 8
style = "bold white"

[python]
python_binary = ['./venv/bin/python', 'python', 'python3']
pyenv_version_name = true

# Components with Dracula Starship Theme
[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold sky)"

[cmd_duration]
style = "bold"
format = "[$duration]($style)"

[directory]
style = "bold lavender"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[git_branch]
style = "bold pink"
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
style = "bold peach"
format = '([\[$all_status$ahead_behind\]]($style) )'

[hostname]
style = "bold"
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
disabled = true

[username]
style_user = "bold"
format = "[$user]($style) on "
show_always = false  

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
